chore_names = ["Sweeping / Mopping", "Dishwashing", "Taking Out Trash", "Cleaning Bathroom", "Buying Groceries"] chore_frequency = ["Daily", "After meals", "Every other day", "Weekly", "Weekly"] print("=" * 50) print("DORM ROOM -- CHORE LIST") print("=" * 50) room_monitor = input("Room monitor name: ") room_number = input("Room number: ") print("\n" + "=" * 50) print(" DORM ROOM -- CHORE LIST") print("=" * 50) for i in range(5): print(f"{i + 1}. {chore_names[i]:<20} [{chore_frequency[i]}]") print("=" * 50) assigned_chores = [] assigned_roommates = [] assigned_status = [] for chore_slot in range(1, 5): print(f"\n--- CHORE {chore_slot} ---") chore_number = int(input("Chore number (0 to skip): ")) if chore_number == 0: print(f"Chore {chore_slot} : skipped (chore = 0)") continue if 1 <= chore_number <= 5: roommate_name = input("Roommate name: ") status = input("Status (done/not done): ") assigned_chores.append(chore_number) assigned_roommates.append(roommate_name) assigned_status.append(status) else: print("Invalid chore number! Please enter 1-5.") completed_count = 0 for status in assigned_status: if status == "done": completed_count += 1 total_assigned = len(assigned_chores) if total_assigned > 0: completion_rate = (completed_count / total_assigned) * 100 completion_rate = int(completion_rate) else: completion_rate = 0 if completion_rate == 100: room_status = "ROOM IS SPOTLESS!" elif completion_rate >= 50: room_status = "ALMOST THERE!" else: room_status = "NEEDS CATCHING UP!" print("\n" + "=" * 45) print("ROOM " + room_number + " -- WEEKLY CHORE REPORT") print("=" * 45) print(f"Room Monitor : {room_monitor}\n") for i in range(len(assigned_chores)): chore_num = assigned_chores[i] chore_name = chore_names[chore_num - 1] chore_freq = chore_frequency[chore_num - 1] roommate = assigned_roommates[i] status = assigned_status[i] print(f"[{i + 1}] {chore_name:<25} [{chore_freq}]") print(f" Roommate : {roommate}") print(f" Status : {status}\n") print("=" * 45) print(f"Completed : {completed_count} out of {total_assigned} assigned") print(f"Completion Rate: {completion_rate}%") print(f"Room Status : {room_status}") print("=" * 45)
• 

























































































